FROM matterlabs/zk-environment:latest2.0-lightweight-nightly

RUN git clone https://github.com/matter-labs/zksync-era /usr/src/zksync
WORKDIR /usr/src/zksync

# checkout to stable tag
RUN git fetch --tags
RUN git checkout core-v21.0.2

RUN zk

ENTRYPOINT [ "zk" ]