@startuml
Client -> L1Resolver: lookup alex.click.eth
L1Resolver --> Client: revert OffchainLookup()
Client -> Gateway: fetch alex storage with its proof from L2Resolver contract on ZkSync
Gateway -> L2Provider: zks_getProof
L2Provider --> Gateway: ZksyncProofResponse
Gateway --> Client: zksync proof for alex name on L2Resolver
Client -> L1Resolver: verify proof is valid
L1Resolver --> Client: verified
@enduml