name: checks

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nodlecode/devcontainer-rollup
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: yarn

      - name: Spell Check
        run: yarn spellcheck

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: forge test --zksync
